# Generated by Django 3.2.6 on 2022-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='요약')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
